name: Build epub

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: nelonoel/branch-name@v1.0.1

    - name: Build book
      env:
        VERSION: 0.0.${{ github.run_number }}
      run: |-
        sudo apt-get install -y ruby-full build-essential zlib1g-dev python
        echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
        echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
        echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        sudo gem install jekyll bundler jekyll-contentful-data-import
        cd scripts
        ./create-k8s.sh

    - name: Validate HTML
      run: python ./scripts/html5check.py -h ./_site/k8s/book.html

    - name: Install Calibre
      run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    
    - name: Convert to PDF
      run: ebook-convert _site/k8s/MyBook.epub _site/k8s/MyBook.pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 0.0.${{ github.run_number }}-${{ env.BRANCH_NAME }}
        release_name: Release 0.0.${{ github.run_number }}-${{ env.BRANCH_NAME }}
        draft: github.ref != 'refs/heads/main'
        prerelease: github.ref != 'refs/heads/main'

    - name: Upload EPUB Release Asset
      id: upload-release-asset-epub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: _site/k8s/MyBook.epub
        asset_name: tenpillarsk8s.epub
        asset_content_type: application/zip

    - name: Upload PDF Release Asset
      id: upload-release-asset-pdf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: _site/k8s/MyBook.pdf
        asset_name: tenpillarsk8s.pdf
        asset_content_type: application/pdf

    - name: Build printable EPUB
      env:
        VERSION: 0.0.${{ github.run_number }}
      run: |-
        cd scripts
        ./create-k8skdp.sh

    - name: Upload Printable EPUB Release Asset
      id: upload-release-asset-printable-epub
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: _site/k8s/MyBookKDP.epub
        asset_name: tenpillarsk8s-printable.epub
        asset_content_type: application/zip